import Head from "next/head";

export function HeadPersonal({title}){
    return(
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
    )
}